server:
  port: 6666
  servlet:
    context-path: /api

mybatis-plus:
  #  configuration:
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.easypan.entity
  global-config:
    banner: off

spring:
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  mail:
    host: smtp.qq.com
    port: 465
    username: 2350542910@qq.com
    password: nmymfmoqqeifebdd
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
        debug: true
  web:
    resources:
      add-mappings: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.138.88.141:3306/easycom?useSSL=false&serverTimezone=UTC
    username: root
    password: luzhihuan
  main:
    banner-mode: off
  data:
    redis:
      host: 8.138.88.141
      port: 6379
      password: 12345
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s
      database: 2


project:
  folder: f:/git_clone/togenter/easycom


admin:
  emails: test@qq.com,2350542910@qq.com

